# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnstockCompany',
            fields=[
                ('article_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('art_source', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('stock_code', models.CharField(blank=True, max_length=45, null=True)),
                ('bull_bear', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cnstock_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('art_source', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('stock_code', models.CharField(blank=True, max_length=45, null=True)),
                ('bull_bear', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'table_name',
                'managed': False,
            },
        ),
    ]
